=== Augustyn/pip2017/src/main/resources/pipeline.dtd
<!ELEMENT pipeline (pipelinechain*)>

<!ELEMENT pipelinechain (pipelinelink*)>
<!ATTLIST pipelinechain
          name ID #REQUIRED
          headlink IDREF #REQUIRED>

<!ELEMENT pipelinelink (processor,transition*)>
<!ATTLIST pipelinelink
          name ID #REQUIRED>

<!ELEMENT processor EMPTY>
<!ATTLIST processor
          bean CDATA #IMPLIED>

<!ELEMENT transition EMPTY
<!ATTLIST transition
          returnvalue CDATA #REQUIRED
          link IDREF #REQUIRED>

=== Augustyn/pip2017/src/main/resources/pipeline.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pipeline SYSTEM "pipeline.dtd">

<pipeline>

	<pipelinechain name="processMessage" headlink="executeValidateForCheckoutChain">
		<pipelinelink name="executeValidateForCheckoutChain">
			<processor bean="/atg/commerce/order/processor/ExecuteValidateForCheckoutChain" />
			<transition returnvalue="1" link="purgeExcessOrderData" />
			<transition returnvalue="0" />
		</pipelinelink>
		<pipelinelink name="purgeExcessOrderData">
			<processor bean="/atg/commerce/order/processor/PurgeExcessOrderData" />
		</pipelinelink>
	</pipelinechain>

</pipeline>
